### ISSUE TITLE
How to use the snippet?

### ISSUE THREAD

**Issue by jaichugani** [thyrc/mexmin#1]
Hi, how do I use this?

Is there any code available I can upload to functions.php?

**Comment by thyrc** [comment]
This [Rust](https://www.rust-lang.org/) crate provides just a minimal command line interface around the [maxminddb](https://crates.io/crates/maxminddb) library. 

You _could_ use it by compiling the code and calling the binary from PHP, I guess, if that is what you meant. But you probably shouldn't. Why not use MaxMind's PHP API instead?
